### ISSUE TITLE
Any docoments on the structure of RHEEM?

### ISSUE THREAD

**Issue by zhipeng93** [rheem-ecosystem/rheem#76]
Hi,

Is there any documents on APIs of RHEEM? Like usage of the important classes, like DataQuantaBuilder, etc? 
Also, can you explain how RHEEM submit jobs to other platforms like a spark cluster?

**Comment by sekruse** [comment]
Hi @ghandzhipeng,

we have the following resources for getting started with Rheem:
- JavaDocs and ScalaDocs within the source code (see also how to build [JavaDocs](https://maven.apache.org/plugins/maven-javadoc-plugin/usage.html) and [ScalaDocs](http://davidb.github.io/scala-maven-plugin/example_doc.html) with Maven)
- the [readme of this repository](https://github.com/rheem-ecosystem/rheem/blob/master/README.md)
- a bunch of example applications in the [rheem-benchmark repository](https://github.com/rheem-ecosystem/rheem-benchmark)

If you have questions on how to use Rheem rather than encountering general problems or limitations, I would like to encourage you to join our [Gitter channel](https://gitter.im/rheem-ecosystem/Lobby), where we can discuss things much more interactively.
